apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: colorforge-backend-pipeline
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: colorforge
    app.kubernetes.io/component: backend
spec:
  description: |
    CI/CD Pipeline DevSecOps para ColorForge Go API.

    Stages:
    1. Clone
    2. Gitleaks (Secret Scan) - paralelo com Test
    3. Test + OWASP (SCA)
    4. SonarQube (SAST) - paralelo com Build Image
    5. Build Image
    6. Trivy Scan (Container)
    7. Update Manifests (GitOps)

    DevSecOps:
    - Gitleaks: Scan de secrets no código
    - OWASP: Vulnerabilidades em dependências (govulncheck)
    - SonarQube: Análise estática de segurança
    - Trivy: Vulnerabilidades em containers
  params:
    # Git parameters
    - name: git-url
      type: string
      description: Git repository URL
      default: https://github.com/r7next/mycolorforge-service.git
    - name: git-revision
      type: string
      description: Git revision to build
      default: main

    # Image parameters
    - name: image-registry
      type: string
      description: Container registry URL
      default: harbor.local
    - name: image-repository
      type: string
      description: Image repository path
      default: colorforge/backend
    - name: image-tag
      type: string
      description: Image tag
      default: latest

    # Build parameters
    - name: go-version
      type: string
      default: "1.23"
    - name: coverage-threshold
      type: string
      default: "0"

    # Registry options
    - name: skip-tls-verify
      type: string
      description: Skip TLS verification for self-signed certs
      default: "true"

    # Security parameters
    - name: security-scan-enabled
      type: string
      description: Enable security scans (Gitleaks, OWASP)
      default: "true"
    - name: fail-on-security-issues
      type: string
      description: Fail pipeline on security issues
      default: "false"

    # SonarQube parameters
    - name: sonar-enabled
      type: string
      description: Enable SonarQube analysis
      default: "true"
    - name: sonar-quality-gate
      type: string
      description: Wait for Quality Gate result
      default: "false"

    # GitOps parameters
    - name: manifest-repo
      type: string
      description: Repository containing Kubernetes manifests
      default: https://github.com/r7next/mycolorforge-infra.git
    - name: overlay-path
      type: string
      description: Path to Kustomize overlay
      default: k8s/overlays/staging

  workspaces:
    - name: shared-workspace
      description: Shared workspace for pipeline tasks
    - name: go-cache
      description: Go module and build cache (persistente)
    - name: trivy-cache
      description: Trivy vulnerability database cache
    - name: docker-credentials
      description: Docker config.json for registry authentication
    - name: git-credentials
      description: Git credentials for cloning and pushing
      optional: true

  tasks:
    # Stage 1: Clone repository
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
        - name: basic-auth
          workspace: git-credentials
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: depth
          value: "1"

    # Stage 2a: Gitleaks - Secret Scanning (paralelo com test)
    - name: gitleaks
      taskRef:
        name: gitleaks-scan
      runAfter:
        - clone
      when:
        - input: "$(params.security-scan-enabled)"
          operator: in
          values: ["true"]
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: source-path
          value: apps/api
        - name: fail-on-leak
          value: $(params.fail-on-security-issues)

    # Stage 2b: Run tests (paralelo com gitleaks)
    - name: test
      taskRef:
        name: golang-test
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: cache
          workspace: go-cache
      params:
        - name: context
          value: apps/api
        - name: packages
          value: "./..."
        - name: go-version
          value: $(params.go-version)
        - name: coverage-threshold
          value: $(params.coverage-threshold)
        - name: timeout
          value: "10m"

    # Stage 2c: OWASP Dependency Check (paralelo com gitleaks e test)
    - name: owasp
      taskRef:
        name: owasp-dependency-check
      runAfter:
        - clone
      when:
        - input: "$(params.security-scan-enabled)"
          operator: in
          values: ["true"]
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: project-type
          value: go
        - name: source-path
          value: apps/api
        - name: fail-on-cvss
          value: "7"

    # Stage 3a: SonarQube Analysis (paralelo com build-image, após test)
    - name: sonarqube
      taskRef:
        name: sonarqube-scan
      runAfter:
        - test
      when:
        - input: "$(params.sonar-enabled)"
          operator: in
          values: ["true"]
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: project-key
          value: colorforge-backend
        - name: project-name
          value: "ColorForge Backend API"
        - name: project-version
          value: $(params.image-tag)
        - name: source-path
          value: apps/api
        - name: language
          value: go
        - name: coverage-report
          value: coverage.out
        - name: quality-gate-wait
          value: $(params.sonar-quality-gate)
        - name: exclusions
          value: "**/vendor/**,**/*_test.go,**/mocks/**"

    # Stage 3b: Build container image (paralelo com sonarqube, após test)
    - name: build-image
      taskRef:
        name: kaniko-build
      runAfter:
        - test
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: image
          value: $(params.image-registry)/$(params.image-repository)
        - name: tag
          value: $(params.image-tag)
        - name: dockerfile
          value: Dockerfile
        - name: context
          value: apps/api
        - name: cache
          value: "true"
        - name: cache-repo
          value: $(params.image-registry)/$(params.image-repository)-cache
        - name: skip-tls-verify
          value: $(params.skip-tls-verify)

    # Stage 4: Trivy - Container Vulnerability Scan
    - name: trivy-scan
      taskRef:
        name: trivy-scan
      runAfter:
        - build-image
      workspaces:
        - name: cache
          workspace: trivy-cache
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: image
          value: $(params.image-registry)/$(params.image-repository):$(params.image-tag)
        - name: severity
          value: "HIGH,CRITICAL"
        - name: exit-code
          value: "0"
        - name: skip-tls-verify
          value: $(params.skip-tls-verify)

    # Stage 5: Update Kubernetes manifests (GitOps)
    - name: update-manifests
      taskRef:
        name: kustomize-update
      runAfter:
        - trivy-scan
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: basic-auth
          workspace: git-credentials
      params:
        - name: git-url
          value: $(params.manifest-repo)
        - name: git-branch
          value: main
        - name: overlay-path
          value: $(params.overlay-path)
        - name: image-name
          value: $(params.image-registry)/$(params.image-repository)
        - name: new-tag
          value: $(params.image-tag)
        - name: new-digest
          value: $(tasks.build-image.results.image-digest)

  results:
    - name: image-url
      description: Full image URL with digest
      value: $(tasks.build-image.results.image-url)
    - name: commit-sha
      description: Git commit that was built
      value: $(tasks.clone.results.commit)
    - name: test-coverage
      description: Test coverage percentage
      value: $(tasks.test.results.coverage)
