# =============================================================================
# Sealed Secrets Example
# =============================================================================
# This file shows how to use Bitnami Sealed Secrets for managing sensitive data.
# Sealed Secrets encrypts your secrets so they can be safely stored in git.
#
# Prerequisites:
# 1. Install Sealed Secrets controller:
#    kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.5/controller.yaml
#
# 2. Install kubeseal CLI:
#    brew install kubeseal  # macOS
#    # or download from https://github.com/bitnami-labs/sealed-secrets/releases
#
# Usage:
# 1. Create a regular secret YAML (don't commit this!)
# 2. Seal it: kubeseal --format yaml < secret.yaml > sealed-secret.yaml
# 3. Commit the sealed-secret.yaml (safe to store in git)
# =============================================================================

# Example: Creating Harbor credentials
# -------------------------------------
# Step 1: Create a temporary secret file (secret-harbor.yaml):
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: harbor-credentials
#   namespace: tekton-pipelines
# type: kubernetes.io/dockerconfigjson
# stringData:
#   .dockerconfigjson: |
#     {
#       "auths": {
#         "harbor.example.com": {
#           "auth": "dXNlcm5hbWU6cGFzc3dvcmQ=",
#           "username": "myuser",
#           "password": "mypassword"
#         }
#       }
#     }
#
# Step 2: Seal the secret:
# kubeseal --format yaml --scope namespace-wide \
#   --namespace tekton-pipelines \
#   < secret-harbor.yaml > sealed-harbor-credentials.yaml
#
# Step 3: Delete the original secret file and commit the sealed version

---
# Example sealed secret (this is what gets committed to git)
# The encryptedData can only be decrypted by the Sealed Secrets controller
# in your specific cluster.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-credentials
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: mycolorforge
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    # This would be the actual encrypted data from kubeseal
    .dockerconfigjson: AgBy8BH0xM... # truncated, real value would be much longer
  template:
    metadata:
      name: harbor-credentials
      namespace: tekton-pipelines
      labels:
        app.kubernetes.io/part-of: mycolorforge
      annotations:
        tekton.dev/docker-0: https://harbor.example.com
    type: kubernetes.io/dockerconfigjson

---
# Alternative: External Secrets Operator
# ======================================
# If you prefer to use a secrets manager (HashiCorp Vault, AWS Secrets Manager, etc.),
# use External Secrets Operator instead.
#
# Prerequisites:
# 1. Install External Secrets Operator:
#    helm repo add external-secrets https://charts.external-secrets.io
#    helm install external-secrets external-secrets/external-secrets -n external-secrets --create-namespace
#
# 2. Configure a SecretStore for your backend (example for HashiCorp Vault):

# apiVersion: external-secrets.io/v1beta1
# kind: ClusterSecretStore
# metadata:
#   name: vault-backend
# spec:
#   provider:
#     vault:
#       server: "https://vault.example.com"
#       path: "secret"
#       version: "v2"
#       auth:
#         kubernetes:
#           mountPath: "kubernetes"
#           role: "external-secrets"

---
# Example ExternalSecret that fetches from Vault
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: harbor-credentials
#   namespace: tekton-pipelines
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: vault-backend
#   target:
#     name: harbor-credentials
#     creationPolicy: Owner
#     template:
#       type: kubernetes.io/dockerconfigjson
#       data:
#         .dockerconfigjson: |
#           {
#             "auths": {
#               "harbor.example.com": {
#                 "auth": "{{ .auth | b64enc }}",
#                 "username": "{{ .username }}",
#                 "password": "{{ .password }}"
#               }
#             }
#           }
#   data:
#     - secretKey: username
#       remoteRef:
#         key: mycolorforge/harbor
#         property: username
#     - secretKey: password
#       remoteRef:
#         key: mycolorforge/harbor
#         property: password
#     - secretKey: auth
#       remoteRef:
#         key: mycolorforge/harbor
#         property: auth
