---
# Harbor registry credentials
# IMPORTANT: These are placeholders. Create the actual secret in the cluster:
#
# Option 1 - Use the existing secret (already created):
#   Secret Name: harbor-registry-credentials
#   Namespace: tekton-pipelines
#   Robot Account: robot$colorforge+tekton-push
#
# Option 2 - Create manually:
#   kubectl create secret docker-registry harbor-registry-credentials \
#     --docker-server=harbor.local \
#     --docker-username='robot$colorforge+tekton-push' \
#     --docker-password='<robot-token>' \
#     -n tekton-pipelines
#
# This file is for reference only - do NOT commit real credentials
apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-credentials
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: colorforge
  annotations:
    tekton.dev/docker-0: https://harbor.local
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "harbor.local": {
          "auth": "PLACEHOLDER_BASE64_ROBOT_CREDENTIALS",
          "username": "robot$colorforge+tekton-push",
          "password": "PLACEHOLDER_ROBOT_TOKEN"
        }
      }
    }
---
# GitHub Git credentials for cloning private repos
# Create PAT at: https://github.com/settings/tokens
# Required scopes: repo (Full control of private repositories)
apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: colorforge
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: r7next
  password: PLACEHOLDER_GITHUB_PAT
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
    [user]
      name = Tekton Pipeline
      email = tekton@colorforge.local
  .git-credentials: |
    https://r7next:PLACEHOLDER_PAT@github.com
---
# GitHub webhook secret for validating incoming webhooks
# Generate with: openssl rand -hex 20
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-secret
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: colorforge
type: Opaque
stringData:
  token: PLACEHOLDER_WEBHOOK_SECRET
---
# PostgreSQL credentials for migrations
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: colorforge
type: Opaque
stringData:
  username: colorforge
  password: PLACEHOLDER_POSTGRES_PASSWORD
---
# Persistent Volume Claims for caching
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-cache-pvc
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: colorforge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-cache-pvc
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: colorforge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-cache-pvc
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/part-of: colorforge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
