apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: colorforge
  labels:
    app: postgres
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.68.202
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
